### ISSUE TITLE
Invalid resource group 'XXXXXXXXX' does not result in Job Failure

### ISSUE THREAD

**Issue by parlevjo2** [diecknet/Simple-Azure-VM-Start-Stop#1] opened 2023-08-22 11:25 UTC
`Get-AzVM : Resource group 'XXXXXXXX' could not be found. ErrorCode: ResourceGroupNotFound ErrorMessage: Resource group 'XXXXXXXX' could not be found. ErrorTarget: StatusCode: 404 ReasonPhrase: Not Found OperationID : 91c0a45d-66f9-49f7-a464-ce7113a2bc61 At line:133 char:16 + ... $VMs = Get-AzVM -ResourceGroupName $ResourceGroupName -VMName $V ... + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ + CategoryInfo : CloseError: (:) [Get-AzVM], ComputeCloudException + FullyQualifiedErrorId : Microsoft.Azure.Commands.Compute.GetAzureVMCommand`

The status of the Job gives `Completed`

By the way, Thanks for the script. I am very happy with it. Much better than the old graphic powershell scripts: `StartAzureV2VMs/StopAzureV2VMs`

**Comment by diecknet** [comment] 2023-08-22 20:54
Thanks for pointing out this issue. I'll try to reproduce the problem and create a fix at some point. I can't promise when that will happen though.

**Comment by diecknet** [comment] 2023-09-21 17:33
I could reproduce the issue. The problem was that the Azure PowerShell module does not treat that error as terminating. I added `-ErrorAction Stop` to treat any error with `Get-AzVm` as terminating. The code is fixed with PR #4.

**Closed as completed by diecknet** 2023-09-21 17:33 UTC
